schema_version = 1
definitions = [
  "docker",
  "dotnet-directory-build",
  "dotnet-global",
  "dotnet-nuget",
  "extra-ansible",
  "extra-basedpyright",
  "extra-biome",
  "extra-composer",
  "extra-eslint",
  "extra-just",
  "extra-justfile",
  "extra-markdownlint",
  "extra-mise",
  "extra-mix",
  "extra-mypy",
  "extra-next",
  "extra-nx",
  "extra-oxlint",
  "extra-playwright",
  "extra-poetry",
  "extra-pre-commit",
  "extra-prettier",
  "extra-prisma",
  "extra-pytest",
  "extra-quarto",
  "extra-rspec",
  "extra-rubocop",
  "extra-ruff",
  "extra-sops",
  "extra-swift",
  "extra-task",
  "extra-tsc",
  "extra-turbo",
  "extra-uv",
  "extra-yamllint",
  "git",
  "go",
  "infra-helm",
  "infra-opentofu",
  "infra-terraform",
  "java-gradle",
  "java-make",
  "java-mvn",
  "js-npm",
  "js-npm-lock",
  "js-pnpm",
  "python-pipfile",
  "python-pyproject",
  "python-requirements",
  "ruby",
  "rust"
]
