schema_version = 1
definitions = [
  "docker",
  "dotnet-directory-build",
  "dotnet-global",
  "dotnet-nuget",
  "extra-eslint",
  "extra-mypy",
  "extra-next",
  "extra-playwright",
  "extra-prettier",
  "extra-prisma",
  "extra-pytest",
  "extra-rspec",
  "extra-rubocop",
  "extra-ruff",
  "extra-tsc",
  "git",
  "go",
  "infra-helm",
  "infra-terraform",
  "java-gradle",
  "java-make",
  "java-mvn",
  "js-npm",
  "js-npm-lock",
  "js-pnpm",
  "python-pipfile",
  "python-pyproject",
  "python-requirements",
  "ruby",
  "rust"
]
