Args = --no-fallback \
       -H:+ReportExceptionStackTraces \
       --initialize-at-build-time=org.slf4j \
       --initialize-at-build-time=org.jboss.logging \
       --initialize-at-run-time=org.sqlite.JDBC,org.sqlite.core.NativeDB,org.sqlite.core.DB
